### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [karek314/iOS-App-Security-Class#1]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks an ```Installation Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Installation Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by lfarah** [comment]
I'd have to ask you to fix this before we can approve [your contribution to AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/1286)

**Comment by karek314** [comment]
Hi,
Instead of **Installation** i have created section called **Usage** which in this case i think is more appropriate to call.

**Comment by karek314** [comment]
@lfarah I have also corrected other repository to fit AwesomeIOS standards, it's still as fork, but i have contacted Github support to turn it into independent repository, should be done soon. **Readme.md** has been improved in both.
