### ISSUE TITLE
CoocoaPods

### ISSUE THREAD

**Issue by lfarah** [karek314/iOS-App-Security-Class#2]
I'd be cool to also add CocoaPods support. I've done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by karek314** [comment]
Hi, thanks for reply. Actually i'm not big fan of CocoaPods, especially with such simple projects, it's much simpler to just drag 2 files instead using CocoaPods.
