### ISSUE TITLE
have a error！！！

### ISSUE THREAD

**Issue by kent-william007** [karek314/iOS-App-Security-Class#4]
thanks so much for show the code！
when i run the project in xcode7.2 and open with simulator。it didnt work。
at SecurityClass.m line 147 and line 164 have the same error:kCFNetworkProxiesSOCKSProxy is unavailable :not available on iOS.
how can i slove this error ？
Looking forward to your reply

**Comment by karek314** [comment]
That's weird. I'm sure it was already there in Xcode 7.2 sdk. You should update Xcode to 9.0 (9A235) and try again.

**Comment by immagine** [comment]
Thank you for the code. I need to use your code in my app, I have couple of errors: 
1. 'sys/conf.h' file not found.
2. 'kCFNetworkProxiesSOCKSPort' is unavailable: not available on iOS.

(but if I comment 1st out I get 2nd error)
(am using Xcode 10.0 currently, I also tried Xcode 9.2). Any help?
